### ISSUE TITLE
Suggestion: Use Wit.ai

### ISSUE THREAD

**Issue by librarianmage** [wizardsambolton/Aubrey-voice-recognition#2]
Wit.ai is a free service based on GItHub that allows one to do accurate voice recognition that is easy to train.

**Comment by UnbanTwin** [comment]
that might come in useful thanks!

**Comment by librarianmage** [comment]
That way, it is easier to have commands that mean the same thing, and to
have "variables"

On Tuesday, May 12, 2015, sam bolton notifications@github.com wrote:

> that might come in useful thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wizardsambolton/Aubrey-voice-recognition/issues/2#issuecomment-101399726
> .

## 

Ray A.
